import React, { useState } from 'react';
import {
  Box,
  Button,
  TextField,
  Typography,
  Paper,
  Alert,
  Grid,
  Card,
  CardContent,
  Divider,
  LinearProgress,
  Table,
  TableBody,
  TableCell,
  TableContainer,
  TableHead,
  TableRow,
  Chip,
  Accordion,
  AccordionSummary,
  AccordionDetails,
} from '@mui/material';
import {
  Assessment,
  FileDownload,
  Search,
  ArrowBack,
  CurrencyRupee,
  ExpandMore,
  Category,
} from '@mui/icons-material';
import { useNavigate } from 'react-router-dom';
import ep1 from '../api/ep1';
import global1 from './global1';
import * as XLSX from 'xlsx';

// ── Helpers ──────────────────────────────────────
const fmt = (n = 0) =>
  Number(n).toLocaleString('en-IN', { minimumFractionDigits: 2, maximumFractionDigits: 2 });

const fmtDate = (d) => {
  if (!d) return '—';
  return new Date(d).toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' });
};

// ─────────────────────────────────────────────────
// Main Component
// ─────────────────────────────────────────────────
const FeesStructureReportds = () => {
  const navigate = useNavigate();

  const [academicyear, setAcademicyear] = useState('');
  const [programcode, setProgramcode] = useState('');
  const [semester, setSemester] = useState('');

  const [rows, setRows] = useState([]);
  const [grandTotal, setGrandTotal] = useState(0);
  const [categoryTotals, setCategoryTotals] = useState({});
  const [filters, setFilters] = useState(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');
  const [reportGenerated, setReportGenerated] = useState(false);

  // ── Fetch ────────────────────────────────────────
  const handleGenerateReport = async () => {
    setLoading(true);
    setError('');
    setReportGenerated(false);

    try {
      let url = `/api/v2/feesstructurereportds?colid=${global1.colid}`;
      if (academicyear) url += `&academicyear=${academicyear}`;
      if (programcode)  url += `&programcode=${programcode}`;
      if (semester)     url += `&semester=${semester}`;

      const response = await ep1.get(url);

      if (response.data.success) {
        setRows(response.data.data || []);
        setGrandTotal(response.data.grandTotal || 0);
        setCategoryTotals(response.data.categoryTotals || {});
        setFilters(response.data.filters);
        setReportGenerated(true);
      } else {
        setError('Failed to generate report');
      }
    } catch (err) {
      setError(err.response?.data?.message || 'Error generating report. Please try again.');
    } finally {
      setLoading(false);
    }
  };

  // ── Excel Export ─────────────────────────────────
  const handleExportToExcel = () => {
    if (!rows.length) { setError('No data to export'); return; }

    const header = ['Fee Category', 'Fee Item', 'Amount (₹)', 'Due Date', 'Semester', 'Fee Group', 'Program', 'Academic Year', 'Status'];
    const dataRows = rows.map((r) => [
      r.feecategory,
      r.feeeitem,
      r.amount,
      fmtDate(r.classdate),
      r.semester,
      r.feegroup,
      r.programcode,
      r.academicyear,
      r.status,
    ]);

    const meta = [
      ['FEES STRUCTURE REPORT'],
      ['Institution', global1.name],
      ['Generated By', global1.user],
      ['Academic Year', filters?.academicyear || 'All'],
      ['Program', filters?.programcode || 'All'],
      ['Semester', filters?.semester || 'All'],
      [''],
      header,
      ...dataRows,
      [''],
      ['GRAND TOTAL', '', grandTotal],
    ];

    const wb = XLSX.utils.book_new();
    const ws = XLSX.utils.aoa_to_sheet(meta);
    XLSX.utils.book_append_sheet(wb, ws, 'Fees Structure');
    XLSX.writeFile(wb, `FeesStructure_${filters?.programcode || 'All'}_${filters?.academicyear || 'All'}.xlsx`);
  };

  // Group rows by feecategory for accordion view
  const grouped = rows.reduce((acc, row) => {
    const cat = row.feecategory || 'Uncategorized';
    if (!acc[cat]) acc[cat] = [];
    acc[cat].push(row);
    return acc;
  }, {});

  // ── Render ───────────────────────────────────────
  return (
    <Box sx={{ p: 3, bgcolor: '#f0f4f8', minHeight: '100vh' }}>
      {/* Back Button */}
      <Box sx={{ mb: 2 }}>
        <Button startIcon={<ArrowBack />} onClick={() => navigate('/dashdashfacnew')}>
          Back
        </Button>
      </Box>

      {/* Header */}
      <Box sx={{ mb: 3 }}>
        <Typography
          variant="h4"
          sx={{ fontWeight: 'bold', mb: 0.5, display: 'flex', alignItems: 'center', gap: 1 }}
        >
          <Assessment sx={{ fontSize: 34, color: '#1976d2' }} />
          Fees Structure Report
        </Typography>
        <Typography variant="body2" sx={{ color: '#666' }}>
          {global1.name}
        </Typography>
        <Typography variant="body2" sx={{ color: '#888' }}>
          View fees by Fee Category, Fee Item, Amount &amp; Due Date
        </Typography>
      </Box>

      {/* Filters */}
      <Paper sx={{ p: 3, mb: 3, borderRadius: 2 }}>
        <Typography variant="h6" sx={{ fontWeight: 'bold', mb: 2 }}>
          Filters
        </Typography>

        <Grid container spacing={2} sx={{ mb: 2 }}>
          <Grid item xs={12} sm={6} md={4}>
            <TextField
              fullWidth
              size="small"
              label="Academic Year"
              placeholder="e.g. 2024-2025"
              value={academicyear}
              onChange={(e) => setAcademicyear(e.target.value)}
            />
          </Grid>
          <Grid item xs={12} sm={6} md={4}>
            <TextField
              fullWidth
              size="small"
              label="Program Code"
              placeholder="e.g. CSE, MBA, BCA ..."
              value={programcode}
              onChange={(e) => setProgramcode(e.target.value)}
            />
          </Grid>
          <Grid item xs={12} sm={6} md={4}>
            <TextField
              fullWidth
              size="small"
              label="Semester (optional)"
              placeholder="e.g. 1, 2, 3 ..."
              value={semester}
              onChange={(e) => setSemester(e.target.value)}
            />
          </Grid>
        </Grid>

        <Button
          variant="contained"
          startIcon={<Search />}
          onClick={handleGenerateReport}
          disabled={loading}
        >
          {loading ? 'Generating...' : 'Generate Report'}
        </Button>

        {loading && (
          <Box sx={{ mt: 2 }}>
            <LinearProgress />
            <Typography variant="body2" sx={{ mt: 1, color: '#1976d2' }}>
              Fetching fee structure data...
            </Typography>
          </Box>
        )}

        {error && <Alert severity="error" sx={{ mt: 2 }}>{error}</Alert>}
      </Paper>

      {/* Summary Cards */}
      {reportGenerated && (
        <>
          <Grid container spacing={2} sx={{ mb: 3 }}>
            <Grid item xs={12} sm={6} md={4}>
              <Card sx={{ boxShadow: 2 }}>
                <CardContent sx={{ textAlign: 'center' }}>
                  <Typography variant="body2" sx={{ color: '#666', mb: 0.5 }}>
                    Grand Total Fees
                  </Typography>
                  <Box sx={{ display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 0.5 }}>
                    <CurrencyRupee sx={{ color: '#1976d2', fontSize: 22 }} />
                    <Typography variant="h5" sx={{ fontWeight: 'bold', color: '#1976d2' }}>
                      {fmt(grandTotal)}
                    </Typography>
                  </Box>
                </CardContent>
              </Card>
            </Grid>
            <Grid item xs={12} sm={6} md={4}>
              <Card sx={{ boxShadow: 2 }}>
                <CardContent sx={{ textAlign: 'center' }}>
                  <Typography variant="body2" sx={{ color: '#666', mb: 0.5 }}>
                    Total Records
                  </Typography>
                  <Typography variant="h5" sx={{ fontWeight: 'bold', color: '#2e7d32' }}>
                    {rows.length}
                  </Typography>
                </CardContent>
              </Card>
            </Grid>
            <Grid item xs={12} sm={6} md={4}>
              <Card sx={{ boxShadow: 2 }}>
                <CardContent sx={{ textAlign: 'center' }}>
                  <Typography variant="body2" sx={{ color: '#666', mb: 0.5 }}>
                    Fee Categories
                  </Typography>
                  <Typography variant="h5" sx={{ fontWeight: 'bold', color: '#e65100' }}>
                    {Object.keys(categoryTotals).length}
                  </Typography>
                </CardContent>
              </Card>
            </Grid>
          </Grid>

          {/* Category Totals Quick View */}
          {Object.keys(categoryTotals).length > 0 && (
            <Paper sx={{ p: 2, mb: 3, borderRadius: 2, bgcolor: '#e3f2fd' }}>
              <Typography variant="subtitle2" sx={{ fontWeight: 'bold', mb: 1.5, color: '#1565c0' }}>
                <Category sx={{ fontSize: 16, mr: 0.5, verticalAlign: 'middle' }} />
                Amount by Category
              </Typography>
              <Box sx={{ display: 'flex', flexWrap: 'wrap', gap: 1 }}>
                {Object.entries(categoryTotals).map(([cat, total]) => (
                  <Chip
                    key={cat}
                    label={`${cat}: ₹ ${fmt(total)}`}
                    sx={{ bgcolor: '#1565c0', color: '#fff', fontWeight: 500 }}
                    size="small"
                  />
                ))}
              </Box>
            </Paper>
          )}

          {/* Main Report */}
          <Paper sx={{ p: 3, borderRadius: 2 }}>
            <Box sx={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', mb: 2 }}>
              <Box>
                <Typography variant="h6" sx={{ fontWeight: 'bold' }}>
                  Fee Items — Grouped by Category
                </Typography>
                {filters && (
                  <Typography variant="caption" sx={{ color: '#888' }}>
                    {filters.academicyear ? `AY: ${filters.academicyear}` : 'All Years'}
                    {filters.programcode ? `  |  Program: ${filters.programcode}` : '  |  All Programs'}
                    {filters.semester ? `  |  Sem: ${filters.semester}` : ''}
                  </Typography>
                )}
              </Box>
              <Button
                variant="outlined"
                startIcon={<FileDownload />}
                onClick={handleExportToExcel}
                disabled={rows.length === 0}
              >
                Export Excel
              </Button>
            </Box>

            <Divider sx={{ mb: 2 }} />

            {rows.length === 0 ? (
              <Box sx={{ textAlign: 'center', py: 5 }}>
                <Typography variant="h6" sx={{ color: '#bbb' }}>
                  No fee records found.
                </Typography>
                <Typography variant="body2" sx={{ color: '#ccc', mt: 1 }}>
                  Try adjusting the filters.
                </Typography>
              </Box>
            ) : (
              <>
                {/* Accordion grouped by category */}
                {Object.entries(grouped).map(([category, catRows], idx) => (
                  <Accordion key={category} defaultExpanded={idx === 0} sx={{ mb: 1, borderRadius: 1, boxShadow: 1 }}>
                    <AccordionSummary expandIcon={<ExpandMore />} sx={{ bgcolor: '#1976d2', color: '#fff', borderRadius: 1 }}>
                      <Box sx={{ display: 'flex', alignItems: 'center', gap: 2, width: '100%' }}>
                        <Typography sx={{ fontWeight: 'bold', flex: 1 }}>
                          {category}
                        </Typography>
                        <Typography sx={{ fontWeight: 'bold', mr: 1 }}>
                          {catRows.length} item{catRows.length > 1 ? 's' : ''} &nbsp;|&nbsp; ₹ {fmt(categoryTotals[category] || 0)}
                        </Typography>
                      </Box>
                    </AccordionSummary>
                    <AccordionDetails sx={{ p: 0 }}>
                      <TableContainer>
                        <Table size="small">
                          <TableHead>
                            <TableRow sx={{ bgcolor: '#e3f2fd' }}>
                              <TableCell sx={{ fontWeight: 'bold' }}>#</TableCell>
                              <TableCell sx={{ fontWeight: 'bold' }}>Fee Item</TableCell>
                              <TableCell align="right" sx={{ fontWeight: 'bold' }}>Amount (₹)</TableCell>
                              <TableCell align="center" sx={{ fontWeight: 'bold' }}>Due Date</TableCell>
                              <TableCell align="center" sx={{ fontWeight: 'bold' }}>Semester</TableCell>
                              <TableCell align="center" sx={{ fontWeight: 'bold' }}>Fee Group</TableCell>
                              <TableCell align="center" sx={{ fontWeight: 'bold' }}>Program</TableCell>
                              <TableCell align="center" sx={{ fontWeight: 'bold' }}>Acad Year</TableCell>
                              <TableCell align="center" sx={{ fontWeight: 'bold' }}>Status</TableCell>
                            </TableRow>
                          </TableHead>
                          <TableBody>
                            {catRows.map((row, rowIdx) => (
                              <TableRow key={rowIdx} hover sx={{ bgcolor: rowIdx % 2 === 0 ? '#fafafa' : '#fff' }}>
                                <TableCell sx={{ color: '#999', fontSize: 12 }}>{rowIdx + 1}</TableCell>
                                <TableCell sx={{ fontWeight: 500 }}>{row.feeeitem || '—'}</TableCell>
                                <TableCell align="right">
                                  <Typography variant="body2" sx={{ color: '#1565c0', fontWeight: 'bold' }}>
                                    ₹ {fmt(row.amount)}
                                  </Typography>
                                </TableCell>
                                <TableCell align="center">
                                  <Chip
                                    label={fmtDate(row.classdate)}
                                    size="small"
                                    sx={{ bgcolor: '#fff3e0', color: '#e65100', fontWeight: 500, fontSize: 11 }}
                                  />
                                </TableCell>
                                <TableCell align="center">{row.semester || '—'}</TableCell>
                                <TableCell align="center">{row.feegroup || '—'}</TableCell>
                                <TableCell align="center">{row.programcode || '—'}</TableCell>
                                <TableCell align="center">{row.academicyear || '—'}</TableCell>
                                <TableCell align="center">
                                  <Chip
                                    label={row.status || 'N/A'}
                                    size="small"
                                    color={row.status === 'Active' ? 'success' : 'default'}
                                  />
                                </TableCell>
                              </TableRow>
                            ))}
                            {/* Category subtotal */}
                            <TableRow sx={{ bgcolor: '#e8f5e9' }}>
                              <TableCell colSpan={2} sx={{ fontWeight: 'bold', fontSize: 13 }}>
                                Subtotal — {category}
                              </TableCell>
                              <TableCell align="right" sx={{ fontWeight: 'bold', color: '#2e7d32', fontSize: 13 }}>
                                ₹ {fmt(categoryTotals[category] || 0)}
                              </TableCell>
                              <TableCell colSpan={6} />
                            </TableRow>
                          </TableBody>
                        </Table>
                      </TableContainer>
                    </AccordionDetails>
                  </Accordion>
                ))}

                {/* Grand Total Row */}
                <Box
                  sx={{
                    mt: 2,
                    p: 2,
                    bgcolor: '#1976d2',
                    borderRadius: 1,
                    display: 'flex',
                    justifyContent: 'space-between',
                    alignItems: 'center',
                    color: '#fff',
                  }}
                >
                  <Typography sx={{ fontWeight: 'bold', fontSize: 16 }}>
                    GRAND TOTAL
                  </Typography>
                  <Typography sx={{ fontWeight: 'bold', fontSize: 18 }}>
                    ₹ {fmt(grandTotal)}
                  </Typography>
                </Box>
              </>
            )}

            {/* Footer */}
            <Box sx={{ mt: 3, pt: 2, borderTop: '1px solid #eee', textAlign: 'center' }}>
              <Typography variant="caption" sx={{ color: '#aaa' }}>
                Report generated on {new Date().toLocaleString('en-IN')} &nbsp;|&nbsp; By: {global1.user}
              </Typography>
            </Box>
          </Paper>
        </>
      )}
    </Box>
  );
};

export default FeesStructureReportds;
