import React, { useState } from 'react';
import {
  Box, Button, Typography, Paper, Alert, Grid,
  Card, CardContent, LinearProgress,
  Table, TableBody, TableCell, TableContainer, TableHead, TableRow,
  Divider,
} from '@mui/material';
import {
  Assessment, FileDownload, Search, AccountBalance, ArrowBack, CurrencyRupee,
} from '@mui/icons-material';
import { useNavigate } from 'react-router-dom';
import ep1 from '../api/ep1';
import global1 from './global1';
import * as XLSX from 'xlsx';

// ── Helpers ───────────────────────────────────────
const fmt = (n = 0) =>
  Number(n).toLocaleString('en-IN', { minimumFractionDigits: 2, maximumFractionDigits: 2 });

const PAYMODES = ['Cash', 'UPI', 'NEFT', 'Cheque', 'PG'];

const thStyle = {
  fontWeight: 'bold', bgcolor: '#1565c0', color: '#fff', whiteSpace: 'nowrap',
};

const SummaryCard = ({ label, value, color = '#1976d2', icon }) => (
  <Card sx={{ boxShadow: 2, height: '100%' }}>
    <CardContent sx={{ textAlign: 'center', py: 2 }}>
      <Typography variant="body2" sx={{ color: '#666', mb: 0.5 }}>{label}</Typography>
      <Box sx={{ display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 0.5 }}>
        {icon && React.cloneElement(icon, { sx: { color, fontSize: 20 } })}
        <Typography variant="h6" sx={{ fontWeight: 'bold', color }}>₹ {fmt(value)}</Typography>
      </Box>
    </CardContent>
  </Card>
);

const today        = new Date().toISOString().split('T')[0];
const firstOfMonth = new Date(new Date().getFullYear(), new Date().getMonth(), 1)
                       .toISOString().split('T')[0];

// ─────────────────────────────────────────────────────────────────────────────
const ProgramWiseCashbookReportDS = () => {
  const navigate = useNavigate();

  // ── Filters ───────────────────────────────────────────────────────────────
  const [fromdate, setFromdate] = useState(firstOfMonth);
  const [todate,   setTodate]   = useState(today);

  // ── Results ───────────────────────────────────────────────────────────────
  const [reportRows,      setReportRows]      = useState([]);
  const [grandTotals,     setGrandTotals]     = useState(null);
  const [loading,         setLoading]         = useState(false);
  const [error,           setError]           = useState('');
  const [reportGenerated, setReportGenerated] = useState(false);

  // ── Fetch report ──────────────────────────────────────────────────────────
  const handleGenerateReport = async () => {
    if (!fromdate || !todate) { 
      setError('Please select both From Date and To Date'); 
      return; 
    }
    setLoading(true); 
    setError(''); 
    setReportGenerated(false);

    try {
      const url = `/api/v2/programwisecashbookreportds?colid=${global1.colid}&fromdate=${fromdate}&todate=${todate}`;
      const response = await ep1.get(url);
      
      if (response.data.success) {
        setReportRows(response.data.data || []);
        setGrandTotals(response.data.grandTotals);
        setReportGenerated(true);
      } else { 
        setError('Failed to generate report'); 
      }
    } catch (err) {
      setError(err.response?.data?.message || 'Error generating report. Please try again.');
    } finally { 
      setLoading(false); 
    }
  };

  // ── Excel Export ──────────────────────────────────────────────────────────
  const handleExportToExcel = () => {
    if (!reportRows.length) { setError('No data to export'); return; }

    const header = ['Program Name', 'Cash', 'UPI', 'NEFT', 'Cheque', 'PG', 'Total (Paymode)', 'Total Amount', 'Total Paid', 'Concession', 'Balance', 'Txns'];
    const rows = reportRows.map(r => [
      r.programcode,
      r.Cash, r.UPI, r.NEFT, r.Cheque, r.PG,
      r.totalPaidByPaymode, r.totalAmount, r.totalPaid, r.totalConcession, r.totalBalance, r.txnCount,
    ]);

    const meta = [
      ['PROGRAM WISE CASHBOOK REPORT'],
      ['Institution',    global1.name],
      ['Generated by',   global1.user],
      ['From Date',      fromdate],
      ['To Date',        todate],
      [''],
      header, ...rows,
      [''],
      ['GRAND TOTAL', grandTotals?.Cash, grandTotals?.UPI, grandTotals?.NEFT, grandTotals?.Cheque, grandTotals?.PG,
       grandTotals?.totalPaidByPaymode, grandTotals?.totalAmount, grandTotals?.totalPaid,
       grandTotals?.totalConcession, grandTotals?.totalBalance, grandTotals?.txnCount],
    ];

    const wb = XLSX.utils.book_new();
    const ws = XLSX.utils.aoa_to_sheet(meta);
    XLSX.utils.book_append_sheet(wb, ws, 'Cashbook Report');
    XLSX.writeFile(wb, `ProgramWiseCashbook_${fromdate}_to_${todate}.xlsx`);
  };

  // ── Render ────────────────────────────────────────────────────────────────
  return (
    <Box sx={{ p: 3, bgcolor: '#f0f4f8', minHeight: '100vh' }}>
      <Box sx={{ mb: 2 }}>
        <Button startIcon={<ArrowBack />} onClick={() => navigate('/dashdashfacnew')}>Back</Button>
      </Box>

      {/* Page Header */}
      <Box sx={{ mb: 3 }}>
        <Typography variant="h4" sx={{ fontWeight: 'bold', mb: 0.5, display: 'flex', alignItems: 'center', gap: 1 }}>
          <Assessment sx={{ fontSize: 34, color: '#1976d2' }} />
          Program Wise Cashbook Report
        </Typography>
        <Typography variant="body2" sx={{ color: '#666' }}>{global1.name}</Typography>
        <Typography variant="body2" sx={{ color: '#888' }}>
          Consolidated collections by Program Code
        </Typography>
      </Box>

      {/* Filters */}
      <Paper sx={{ p: 3, mb: 3, borderRadius: 2 }}>
        <Typography variant="h6" sx={{ fontWeight: 'bold', mb: 2 }}>Date Range Filters</Typography>

        <Grid container spacing={2} sx={{ mb: 2 }}>
          <Grid item xs={12} sm={6} md={3}>
            <Box>
              <Typography variant="caption" sx={{ color: '#666' }}>From Date *</Typography>
              <input type="date" value={fromdate} onChange={e => setFromdate(e.target.value)}
                style={{ display:'block', width:'100%', padding:'8px', borderRadius:4,
                         border:'1px solid #ccc', fontSize:14, marginTop:4 }} />
            </Box>
          </Grid>
          <Grid item xs={12} sm={6} md={3}>
            <Box>
              <Typography variant="caption" sx={{ color: '#666' }}>To Date *</Typography>
              <input type="date" value={todate} onChange={e => setTodate(e.target.value)}
                style={{ display:'block', width:'100%', padding:'8px', borderRadius:4,
                         border:'1px solid #ccc', fontSize:14, marginTop:4 }} />
            </Box>
          </Grid>
          <Grid item xs={12} md={6} sx={{ display:'flex', alignItems:'flex-end' }}>
             <Button variant="contained" startIcon={<Search />}
              onClick={handleGenerateReport} disabled={loading} sx={{ height: 40 }}>
              {loading ? 'Generating...' : 'Generate Report'}
            </Button>
          </Grid>
        </Grid>

        {loading && (
          <Box sx={{ mt: 2 }}>
            <LinearProgress />
            <Typography variant="body2" sx={{ mt: 1, color: '#1976d2' }}>Fetching cashbook data...</Typography>
          </Box>
        )}
        {error && <Alert severity="error" sx={{ mt: 2 }}>{error}</Alert>}
      </Paper>

      {/* Summary Cards */}
      {reportGenerated && grandTotals && (
        <Grid container spacing={2} sx={{ mb: 3 }}>
          {PAYMODES.map(pm => (
            <Grid item xs={6} sm={4} md={2} key={pm}>
              <SummaryCard label={pm} value={grandTotals[pm]}
                color={pm==='Cash'?'#2e7d32':pm==='UPI'?'#1565c0':pm==='NEFT'?'#6a1b9a':pm==='Cheque'?'#e65100':'#00838f'}
                icon={<CurrencyRupee />} />
            </Grid>
          ))}
          <Grid item xs={6} sm={4} md={2}>
            <SummaryCard label="Total Paid" value={grandTotals.totalPaid} color="#4caf50" icon={<AccountBalance />} />
          </Grid>
        </Grid>
      )}

      {/* Report Table */}
      {reportGenerated && (
        <Paper sx={{ p: 3, borderRadius: 2 }}>
          <Box sx={{ display:'flex', justifyContent:'space-between', alignItems:'center', mb: 2 }}>
            <Typography variant="h6" sx={{ fontWeight: 'bold' }}>
              Collection Summary — Program Wise
            </Typography>
            <Button variant="outlined" startIcon={<FileDownload />}
              onClick={handleExportToExcel} disabled={reportRows.length === 0}>
              Export Excel
            </Button>
          </Box>

          <Divider sx={{ mb: 2 }} />

          {reportRows.length === 0 ? (
            <Box sx={{ textAlign:'center', py: 5 }}>
              <Typography variant="h6" sx={{ color:'#bbb' }}>No data found for the selected date range.</Typography>
            </Box>
          ) : (
            <TableContainer>
              <Table size="small" stickyHeader>
                <TableHead>
                  <TableRow>
                    <TableCell sx={{ ...thStyle }}>Program Name</TableCell>
                    {PAYMODES.map(pm => (
                      <TableCell key={pm} align="right" sx={{ ...thStyle }}>{pm}</TableCell>
                    ))}
                    <TableCell align="right" sx={{ ...thStyle, bgcolor:'#0d47a1' }}>Total (Paymode)</TableCell>
                    <TableCell align="right" sx={{ ...thStyle }}>Total Amount</TableCell>
                    <TableCell align="right" sx={{ ...thStyle }}>Total Paid</TableCell>
                    <TableCell align="right" sx={{ ...thStyle }}>Concession</TableCell>
                    <TableCell align="right" sx={{ ...thStyle }}>Balance</TableCell>
                    <TableCell align="center" sx={{ ...thStyle }}>Txns</TableCell>
                  </TableRow>
                </TableHead>
                <TableBody>
                  {reportRows.map((row, idx) => (
                    <TableRow key={idx} hover sx={{ bgcolor: idx % 2 === 0 ? '#fafafa' : '#fff' }}>
                      <TableCell sx={{ fontWeight:600 }}>{row.programcode}</TableCell>
                      {PAYMODES.map(pm => (
                        <TableCell key={pm} align="right">
                          {row[pm] > 0 ? `₹ ${fmt(row[pm])}` : '—'}
                        </TableCell>
                      ))}
                      <TableCell align="right" sx={{ fontWeight:'bold', color:'#0d47a1' }}>₹ {fmt(row.totalPaidByPaymode)}</TableCell>
                      <TableCell align="right">₹ {fmt(row.totalAmount)}</TableCell>
                      <TableCell align="right" sx={{ color:'#4caf50', fontWeight:500 }}>₹ {fmt(row.totalPaid)}</TableCell>
                      <TableCell align="right">{row.totalConcession > 0 ? `₹ ${fmt(row.totalConcession)}` : '—'}</TableCell>
                      <TableCell align="right" sx={{ color: row.totalBalance > 0 ? '#f44336':'#4caf50', fontWeight:500 }}>₹ {fmt(row.totalBalance)}</TableCell>
                      <TableCell align="center">{row.txnCount}</TableCell>
                    </TableRow>
                  ))}
                  {/* Grand Total */}
                  <TableRow sx={{ bgcolor: '#e8f5e9' }}>
                    <TableCell sx={{ fontWeight:'bold' }}>GRAND TOTAL</TableCell>
                    {PAYMODES.map(pm => <TableCell key={pm} align="right" sx={{ fontWeight:'bold', color:'#2e7d32' }}>₹ {fmt(grandTotals[pm])}</TableCell>)}
                    <TableCell align="right" sx={{ fontWeight:'bold', color:'#0d47a1' }}>₹ {fmt(grandTotals.totalPaidByPaymode)}</TableCell>
                    <TableCell align="right" sx={{ fontWeight:'bold' }}>₹ {fmt(grandTotals.totalAmount)}</TableCell>
                    <TableCell align="right" sx={{ fontWeight:'bold', color:'#4caf50' }}>₹ {fmt(grandTotals.totalPaid)}</TableCell>
                    <TableCell align="right" sx={{ fontWeight:'bold', color:'#ff9800' }}>₹ {fmt(grandTotals.totalConcession)}</TableCell>
                    <TableCell align="right" sx={{ fontWeight:'bold', color: grandTotals.totalBalance > 0 ? '#f44336':'#4caf50' }}>₹ {fmt(grandTotals.totalBalance)}</TableCell>
                    <TableCell align="center" sx={{ fontWeight:'bold' }}>{grandTotals.txnCount}</TableCell>
                  </TableRow>
                </TableBody>
              </Table>
            </TableContainer>
          )}

          <Box sx={{ mt: 3, pt: 2, borderTop: '1px solid #eee', textAlign: 'center' }}>
            <Typography variant="caption" sx={{ color: '#aaa' }}>
              Report generated on {new Date().toLocaleString('en-IN')} &nbsp;|&nbsp; By: {global1.user}
            </Typography>
          </Box>
        </Paper>
      )}
    </Box>
  );
};

export default ProgramWiseCashbookReportDS;
